class Rules:
    # Los símbolos semánticos se añaden a las reglas. 
    # Éstas son llamadas por el parser, pero son obviadas por el parsing table.
    def __init__(self):
        self.rules = {
            0: ['#genOF', '#genPLT', '#slice1', '#crearTSG', 'WORLDNAME', '<id>', 'COLON', '<programa>', '#eliminarTSG', '#closePLT', '#slice3', '#closeOF'],
            1: ['IDENTIFIER'],
            2: ['<seccion_de_constantes>', '<seccion_de_tipos>', '<seccion_de_variables>', '#slice2', '<seccion_de_prototipos>', '<seccion_de_rutinas>', '<punto_entrada_del_programa>', 'WORLDSAVE'],
            3: ['#const1', 'BEDROCK', '<constantes>', '#const2'],
            4: [],
            5: ['<constante>', '<constantes>'],
            6: [],
            7: ['OBSIDIAN', '#type1', '<tipo>', '#const3', '<id>', '#const4', '#cgConst', '<literal>'],
            8: ['RESOURCEPACK', '<tipos>'],
            9: [],
            10: ['ANVIL', '<id>', 'ARROW', '<tipo>', 'SEMICOLON', '<tipos>'],
            11: [],
            12: ['INVENTORY', '#var1', '<variables>', '#var2'],
            13: [],
            14: ['<variable>', '<variables>'],
            15: [],
            16: ['#type1', '<tipo>', '#var3', '<id>', 'EQUAL', '#var4', '#cgVar', '<literal>'],
            17: ['RECIPE', '<prototipos>'],
            18: [],
            19: ['<prototipo>', '<prototipos>'],
            20: [],
            21: ['SPELL', '<id>', 'OPENPARENTHESIS', '<parametros>', 'CLOSEPARENTHESIS', 'ARROW', '<tipo>'],
            22: ['#rit1', 'RITUAL', '<id>', 'OPENPARENTHESIS', '<parametros>', 'CLOSEPARENTHESIS', 'SEMICOLON'],
            23: ['CRAFTINGTABLE', '<rutinas>'],
            24: [],
            25: ['<rutina>', '<rutinas>'],
            26: [],
            27: ['SPELL', '<id>', 'OPENPARENTHESIS', '<parametros>', 'CLOSEPARENTHESIS', '<cuerpo_funcion>', 'SEMICOLON'],
            28: ['#rit1', 'RITUAL', '<id>', 'OPENPARENTHESIS', '<parametros>', 'CLOSEPARENTHESIS', '<cuerpo_rutina>', 'SEMICOLON'],
            29: ['SPAWNPOINT', '<cuerpo_rutina>', 'SEMICOLON'],
            30: ['STACK'],
            31: ['RUNE'],
            32: ['SPIDER'],
            33: ['TORCH'],
            34: ['GHAST'],
            35: ['CHAR'],
            36: ['INTEGER'],
            37: ['FLOAT'],
            38: ['ON'],
            39: ['OFF'],
            40: ['STRING', '<acceso>'],
            41: ['OPENSQUAREBRACKET', '<literal>', 'CLOSESQUAREBRACKET'],
            42: [],
            43: ['<literal>'],
            44: [],
            45: ['<literal>', '<mas_parametros>'],
            46: ['<id>', '<mas_parametros>'],
            47: ['COMMA', '<literal_o_variable>'],
            48: [],
            49: ['<secciones>', '#crearTSL', 'POLLOCRUDO', '<inst_exp>', '<return_rutina>', 'POLLOASADO', '#rit2', '#eliminarTSL'],
            50: [],
            51: ['<secciones>', 'POLLOCRUDO', '<inst_exp>', '<return>', 'POLLOASADO'],
            52: [],
            53: ['<return>'],
            54: [],
            55: ['RESPAWN'],
            56: ['<seccion_de_constantes>', '<seccion_de_tipos>', '<seccion_de_variables>'],
            57: ['<instruccion>', '<inst_exp>'],
            58: [],
            59: ['<while>'],
            60: ['<if>'],
            61: ['<switch>'],
            62: ['<repeat>'],
            63: ['<for>'],
            64: ['<break>'],
            65: ['<halt>'],
            66: ['<continue>'],
            67: ['<asignacion>'],
            68: ['ENDERPEARL'],
            69: ['REPEATER', '<condicion>', 'CRAFT', '<inst_exp_o_bloque>'],
            70: ['TARGET', '<condicion>', 'CRAFT', '<cuerpo_if>'],
            71: ['HIT', '<inst_exp_o_bloque>', 'MISS', '<inst_exp_o_bloque>'],
            72: ['JUKEBOX', '<condicion>', 'CRAFT', '<cuerpo_switch>'],
            73: ['<cases>', '<silence>'],
            74: ['<case>', '<cases>'],
            75: [],
            76: ['DISC', '<literal>', 'COLON', '<inst_exp>', 'COMMA', '<break>', 'SEMICOLON'],
            77: ['SILENCE', 'COLON', '<inst_exp>', 'COMMA', '<break>', 'SEMICOLON'],
            78: ['SPAWNER', '<inst_exp>', 'EXHAUSTED', '<condicion>'],
            79: ['WALK', '<index>', '<step>', 'CRAFT', '<inst_exp_o_bloque>'],
            80: ['<id>', 'SET', '<literal>', 'TO', '<literal>'],
            81: ['STEP', '<literal>'],
            82: ['CREEPER'],
            83: ['RAGEQUIT'],
            84: ['<expresion>'],
            85: ['<instruccion>'],
            86: ['POLLOCRUDO', '<cuerpo_bloque_inst>', 'POLLOASADO'],
            87: ['<instruccion>', '<inst_exp>'],
            88: ['<id>', '<op_assignacion>', '<expresion>'],
            89: ['EQUAL'],
            90: ['PLUS_EQUAL'],
            91: ['MINUS_EQUAL'],
            92: ['MULTIPLY_EQUAL'],
            93: ['DIVIDE_EQUAL'],
            94: ['MODULE_EQUAL'],
            95: ['<or>', 'SEMICOLON'],
            96: ['<xor>', '<or_logico>'],
            97: ['OR', '<xor>', '<or_logico>'],
            98: [],
            99: ['<and>', '<xor_logico>'],
            100: ['XOR', '<and>', '<xor_logico>'],
            101: [],
            102: ['<igualdad>', '<and_logico>'],
            103: ['AND', '<igualdad>', '<and_logico>'],
            104: [],
            105: ['<desigualdad>', '<cmp_igualdad>'],
            106: ['IS', '<desigualdad>', '<cmp_igualdad>'],
            107: ['ISNOT', '<desigualdad>', '<cmp_igualdad>'],
            108: [],
            109: ['<dividir_string>', '<cmp_desigual>'],
            110: ['MORETHAN', '<dividir_string>', '<cmp_desigual>'],
            111: ['MOREEQUAL', '<dividir_string>', '<cmp_desigual>'],
            112: ['LESSTHAN', '<dividir_string>', '<cmp_desigual>'],
            113: ['LESSEQUAL', '<dividir_string>', '<cmp_desigual>'],
            114: [],
            115: ['<unir_intersec_string>', '<op_string>'],
            116: ['FROM', '<literal>', '<literal>', 'DOUBLEPOUNDKEY', '<literal>', '<unir_intersec_string>', '<op_string>'],
            117: ['EXCEPT', '<literal>', '<literal>', 'DOUBLEPOUNDKEY', '<literal>', '<unir_intersec_string>', '<op_string>'],
            118: [],
            119: ['<op_lineal>', '<op_union_interec>'],
            120: ['BIND', '<op_lineal>', '<op_union_interec>'],
            121: ['SEEK'],
            122: [],
            123: ['<termino>', '<suma_resta>'],
            124: ['INT_SUM', '<termino>', '<suma_resta>'],
            125: ['INT_MIN', '<termino>', '<suma_resta>'],
            126: ['FLOAT_SUM', '<termino>', '<suma_resta>'],
            127: ['FLOAT_MIN', '<termino>', '<suma_resta>'],
            128: [],
            129: ['<factor>', '<sub_termino>'],
            130: ['INT_MULT', '<factor>', '<sub_termino>'],
            131: ['INT_DIV', '<factor>', '<sub_termino>'],
            132: ['INT_MOD', '<factor>', '<sub_termino>'],
            133: ['FLOAT_MULT', '<factor>', '<sub_termino>'],
            134: ['FLOAT_DIV', '<factor>', '<sub_termino>'],
            135: ['FLOAT_MOD', '<factor>', '<sub_termino>'],
            136: [],
            137: ['<op_unaria>', '<sub_factor>'],
            138: ['#type1','<literal>'],
            139: ['#checkExist','<id>'],
            140: ['OPENPARENTHESIS', '<expresion>', 'CLOSEPARENTHESIS'],
            141: ['ISENGRAVED'],
            142: ['ISINSCRIBED'],
            143: ['NOT'],
            144: ['SOULSAND'],
            145: ['MAGMA'],
            146: ['CAST'],
            147: ['CHUNK'],
            148: ['POUNDKEY'],
            149: ['ETCHUP'],
            150: ['ETCHDOWN'],
            151: []
        }
        
    def getRules(self):
        return self.rules
